default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username]%>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] %>

pre_production:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username]%>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] %>

production:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username]%>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] %>

test:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username]%>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] %>